//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TSCtrlSys.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_TOOL_LOGIN                  101
#define IDS_TOOL_CTRL                   102
#define IDS_TOOL_PARAM_VALVE            103
#define IDS_TOOL_PARAM_DISPENSING       104
#define IDS_TOOL_PARAM                  105
#define IDS_TOOL_CAMERA_LIVE            106
#define IDS_TOOL_CAMERA_STOP            107
#define IDS_TOOL_MARK                   108
#define IDS_TOOL_TEST                   109
#define IDS_TOOL_LACK                   110
#define IDS_TOOL_REPAIR                 111
#define IDS_TOOL_NEEDLE                 112
#define IDS_TOOL_HEIGHT                 113
#define IDS_TOOL_BALANCE                114
#define IDS_TOOL_DEBUG                  115
#define IDS_TOOL_RUN                    116
#define IDS_TOOL_PAUSE                  117
#define IDS_TOOL_STOP                   118
#define IDS_TOOL_VALVE_RESET            119
#define IDS_TOOL_AUTONEEDLE             120
#define IDS_TOOL_IO                     121
#define IDD_DLG_LOGIN                   200
#define IDD_DLG_CTRL                    201
#define IDD_DLG_PROUD                   202
#define IDD_DlG_V9SET                   203
#define IDD_DLG_BLOBSET                 204
#define IDD_DLG_MARKSET                 205
#define IDD_DLG_PATTERN                 206
#define IDD_DLG_REPAIR                  207
#define IDD_DLG_INFO                    208
#define IDD_DlG_IO                      209
#define IDD_PAGE_FACTORY_PARAM          210
#define IDD_PAGE_PLC                    211
#define IDD_DLG_RCD                     212
#define IDP_OLE_INIT_FAILED             300
#define IDP_SOCKETS_INIT_FAILED         301
#define IDS_APP_STATUS                  302
#define IDS_COMPILE_NO                  303
#define IDS_CMD_COUNT                   304
#define IDR_POPUP_EDIT                  305
#define IDS_TOOLBAR_STANDARD            306
#define IDS_TOOLBAR_CUSTOMIZE           307
#define ID_VIEW_CUSTOMIZE               308
#define IDR_MAINFRAME                   309
#define IDR_MAINFRAME_256               310
#define IDR_TSCtrlSysTYPE               311
#define ID_VIEW_OUTPUTWND               312
#define ID_SORTPROPERTIES               313
#define ID_PROPERTIES1                  314
#define ID_PROPERTIES2                  315
#define ID_EXPAND_ALL                   316
#define IDS_OUTPUT_WND                  317
#define IDS_PROPERTIES_WND              318
#define IDI_OUTPUT_WND                  319
#define IDI_OUTPUT_WND_HC               320
#define IDI_PROPERTIES_WND              321
#define IDI_PROPERTIES_WND_HC           322
#define IDR_OUTPUT_POPUP                323
#define IDR_PROPERTIES                  324
#define IDB_PROPERTIES_HC               325
#define ID_VIEW_NAVIGATION              326
#define IDB_NAVIGATION_LARGE            327
#define IDB_NAVIGATION_LARGE_HC         328
#define IDB_PAGES                       329
#define IDB_PAGES_HC                    330
#define IDB_PAGES_SMALL                 331
#define IDB_PAGES_SMALL_HC              332
#define IDR_THEME_MENU                  333
#define IDR_MAINFRAME1                  334
#define ID_VIEW_APPLOOK_WIN_2000        335
#define ID_VIEW_APPLOOK_OFF_XP          336
#define ID_VIEW_APPLOOK_WIN_XP          337
#define ID_VIEW_APPLOOK_OFF_2003        338
#define ID_VIEW_APPLOOK_VS_2005         339
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   340
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  341
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 342
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   343
#define IDS_CALENDAR                    344
#define IDS_SHORTCUTS                   345
#define IDS_FOLDERS                     346
#define IDS_OUTLOOKBAR                  347
#define IDS_BUILD_TAB                   348
#define IDS_DEBUG_TAB                   349
#define IDS_FIND_TAB                    350
#define IDS_EDIT_MENU                   351
#define IDR_241                         352
#define IDB_BITMAP_MOVE                 353
#define IDB_BITMAP2_UP                  355
#define IDB_BITMAP1_DOWN                356
#define IDB_BITMAPH_UP                  357
#define IDB_BITMAPH_DOWN                358
#define IDB_BNTMOVE                     359
#define ID_CMD_REOPEN_FILE              360
#define ID_FILE_OPEN_DXF                361
#define ID_LOGOFF                       362
#define ID_LOGON                        363
#define ID_VIEW_SYS_INFO                364
#define IDR_HTML_PAGEFEEDER             365
#define IDR_HTML_DLGAUTONEEDLE          366
#define IDD_DLG_HEIGHT                  378
#define IDD_DLG_NEEDLE                  379
#define IDD_DLG_ALIGN_NEEDLE            382
#define IDB_BITMAP_SENSOR_OFF           384
#define IDB_BITMAP_SENSOR_ON            385
#define IDD_DLG_CUSTOM                  386
#define IDD_DLG_AUTO_ALIGN              387
#define IDD_DLG_PROMPT                  391
#define IDD_DLG_MANUAL_ALIGN            395
#define IDD_DLG_USER_REGISTER           396
#define IDD_DLG_DEBUG_NEEDLE            397
#define IDD_DLG_DEBUG_HEIGHT            398
#define IDD_DLG_SET_MARK                399
#define IDD_DLG_IMAGE_POSITION          400
#define IDD_DLG_SET_POSITION            401
#define IDD_DLG_CONFIGURE               402
#define IDD_DLG_PAD_DETECT              403
#define IDD_DLG_HEIGHT_CALIB            404
#define IDD_DLG_DETECT_CALIB            405
#define IDD_DLG_HEIGHT_POSITION         406
#define IDB_BITMAP_ADJUST               407
#define IDD_DLG_LABEL                   408
#define IDD_DLG_AUTO_NEEDLE             409
#define IDB_BITMAP1                     418
#define IDD_DLG_DETECT_BASEPIONT        420
#define IDD_DLG_NEEDLEADJUST            421
#define IDD_DLG_CAMERA_ADJUST           422
#define IDD_DLG_NEEDLECAMERA            423
#define IDD_DLG_NEEDLEONE               424
#define IDD_DLG_NEEDLEONE_ADJUST        425
#define IDD_DLG_NEEDLETHREE             426
#define IDD_DLG_NEEDLETHREE_ADJUST      427
#define IDD_DLG_NEEDLETWO               428
#define IDD_DLG_NEEDLETWO_ADJUST        429
#define IDD_DIALOG1                     430
#define IDD_DLG_CAMERALASER             430
#define IDD_DLG_DOWN                    431
#define IDD_DLG_RUNINFO                 432
#define IDD_DLG_VALVEHEAT               433
#define IDD_DLG_URLPROMPT               434
#define IDD_DIALOG2                     435
#define IDD_DLG_MATERIALCODE            435
#define IDC_STATIC_APP                  1000
#define IDC_CHECK_PAUSE_CLEAN_TEST      1001
#define IDC_EDIT_MAX_ADJUST_X           1002
#define IDC_EDIT_MAX_ADJUST_Y           1003
#define IDC_RADIO_GRAYSCALE             1004
#define IDC_RADIO_GEOMETRIC             1005
#define IDC_CHECK_PAD_DETECT            1006
#define IDC_CHECK_ADJUST_NEEDLE         1007
#define IDC_EDIT_FIRST_ROW              1100
#define IDC_EDIT_FIRST_COLUMN           1101
#define IDC_EDIT_FIRST_ROWD             1102
#define IDC_EDIT_FIRST_COLUMND          1103
#define IDC_EDIT_SECOND_ROW             1104
#define IDC_EDIT_SECOND_COLUMN          1105
#define IDC_EDIT_SECOND_ROWD            1106
#define IDC_EDIT_SECOND_COLUMND         1107
#define IDC_EDIT_THIRD_ROW              1108
#define IDC_EDIT_THIRD_COLUMN           1109
#define IDC_EDIT_THIRD_ROWD             1110
#define IDC_EDIT_THIRD_COLUMND          1111
#define IDC_BTN_FIRST_ROWD              1112
#define IDC_BTN_FIRST_COLUMND           1113
#define IDC_BTN_SECOND_ROWD             1114
#define IDC_BTN_SECOND_COLUMND          1115
#define IDC_BTN_THIRD_ROWD              1116
#define IDC_BTN_THIRD_COLUMND           1117
#define IDC_EDIT_IRREGULAR_ROW_NUM      1118
#define IDC_EDIT_IRREGULAR_COL_NUM      1119
#define IDC_COMBO_IRREGULAR_ROW         1120
#define IDC_COMBO_IRREGULAR_COL         1121
#define IDC_EDIT_IRREGULAR_NEXT_ROW     1122
#define IDC_EDIT_IRREGULAR_NEXT_COL     1123
#define IDC_EDIT_IRREGULAR_ROW_DISTANCE 1124
#define IDC_EDIT_IRREGULAR_COL_DISTANCE 1125
#define IDC_BTN_SAVE_IRREGULAR_ROWD     1126
#define IDC_BTN_SAVE_IRREGULAR_COLUMND  1127
#define IDC_EDIT_SLOT_LENGTH            1128
#define IDC_EDIT_SLOT_WIDTH             1129
#define IDC_EDIT_PRE_DELAY              1130
#define IDC_EDIT_POST_DELAY             1131
#define IDC_EDIT_LINE_VEL               1132
#define IDC_EDIT_LINE_ACC               1133
#define IDC_EDIT_CIRCLE_VEL             1134
#define IDC_EDIT_CIRCLE_ACC             1135
#define IDC_EDIT_LIFT_HEIGHT            1136
#define IDC_EDIT_PAUSE_POS              1137
#define IDC_EDIT_PAUSE_TIME             1138
#define IDC_EDIT_FIRST_DISPDELAY        1139
#define IDC_EDIT_DISP_RADIUS            1140
#define IDC_EDIT_GRABIMAGE_DELAY        1141
#define IDC_EDIT_DISTANCE               1142
#define IDC_EDIT_COMPANGLE              1143
#define IDC_EDIT_CLEAN_DELAY            1144
#define IDC_EDIT_LINE_LENGTH            1145
#define IDC_EDIT_RECT_LENGTH            1146
#define IDC_EDIT_RECT_WIDTH             1147
#define IDC_EDIT_DISPENSE_HEIGHT        1148
#define IDC_EDIT_TEST_DELAY             1149
#define IDC_EDIT_TEST_NUMBER            1150
#define IDC_EDIT_MEASURE_NUMBER         1151
#define IDC_EDIT_TITL_NUMBER            1152
#define IDC_EDIT_TITL_ERROR             1153
#define IDC_EDIT_HEIGHT_ERROR           1154
#define IDC_EDIT_SCAN_DELAY             1155
#define IDC_EDIT_HEIGHT_DELAY           1156
#define IDC_EDIT_DISP_OFFSET_X          1157
#define IDC_EDIT_DISP_OFFSET_Y          1158
#define IDC_EDIT_MAX_OFFSET_ANGLE       1159
#define IDC_FA                          1160
#define IDC_FB                          1161
#define IDC_FC                          1162
#define IDC_FD                          1163
#define IDC_RADIO_NO_INSPECT            1164
#define IDC_RADIO_TRANSITION_INSPECT    1165
#define IDC_RADIO_SCAN_INSPECT          1166
#define IDC_RADIO_SECTION_INSPECT       1167
#define IDC_RADIO_ROW_DISP              1168
#define IDC_RADIO_COLUMN_DISP           1169
#define IDC_BTN_CUSTOM_PARAM            1177
#define IDC_RADIO_IMAGE_NO              1178
#define IDC_RADIO_IMAGE_ONE_MARK        1179
#define IDC_RADIO_IMAGE_TWO_MARK        1180
#define IDC_EDIT_LACK_CMPVALUE          1181
#define IDC_CHECK_FULL_CLEAN            1182
#define IDC_CHECK_SWITCH_ENABLE         1183
#define IDC_CHECK_MEASURE_HEIGHT        1184
#define IDC_CHECK_NOFLOW                1185
#define IDC_CHECK_CLEAN_NEEDLE          1186
#define IDC_CHECK_FIRST_TEST            1187
#define IDC_CHECK_SLOT_DETECT           1188
#define IDC_CHECK_FULL_DISCHARGE        1189
#define IDC_CHECK_TITL_DETECT           1190
#define IDC_CHECK_NO_COMPENSATE         1190
#define IDC_CHECK_IRREGULAR_MATRIX      1191
#define IDC_CHECK_SINGLE_DISP           1192
#define IDC_CHECK_DISP_FINISH_FILL      1193
#define IDC_RADIO_FIRST_CLEAN_LATER_TEST 1194
#define IDC_RADIO_FIRST_TEST_LATER_CLEAN 1195
#define IDC_RADIO_ONE_VALVE             1196
#define IDC_RADIO_TWO_VALVE             1197
#define IDC_RADIO_THREE_VALVE           1198
#define IDC_CHECK_CLEAN_DISCHARGE       1199
#define IDC_BTN_HEIGHT_X_NEG            1200
#define IDC_BTN_HEIGHT_X_POS            1201
#define IDC_BTN_HEIGHT_Y_NEG            1202
#define IDC_BTN_HEIGHT_Y_POS            1203
#define IDC_BTN_HEIGHT_ZA_NEG           1204
#define IDC_BTN_HEIGHT_ZA_POS           1205
#define IDC_BTN_HEIGHT_ZB_NEG           1206
#define IDC_BTN_HEIGHT_ZB_POS           1207
#define IDC_BTN_HEIGHT_ZC_NEG           1208
#define IDC_BTN_HEIGHT_ZC_POS           1209
#define IDC_SLIDER_HEIGHT_SPEED         1210
#define IDC_EDIT_HEIGHT_SPEED           1211
#define IDC_BTN_HEIGHT_A_NEG            1212
#define IDC_BTN_HEIGHT_A_POS            1213
#define IDC_BTN_HEIGHT_B_NEG            1214
#define IDC_BTN_HEIGHT_B_POS            1215
#define IDC_BTN_HEIGHT_C_NEG            1216
#define IDC_BTN_HEIGHT_C_POS            1217
#define IDC_BTN_HEIGHT_D_NEG            1218
#define IDC_BTN_HEIGHT_D_POS            1219
#define IDC_SLIDER_HEIGHT_ADJUST_SPEED  1220
#define IDC_EDIT_HEIGHT_ADJUST_SPEED    1221
#define IDC_EDIT_HEIGHT_CURRENT_X       1222
#define IDC_EDIT_HEIGHT_CURRENT_Y       1223
#define IDC_EDIT_HEIGHT_CURRENT_ZA      1224
#define IDC_EDIT_HEIGHT_CURRENT_ZB      1225
#define IDC_EDIT_HEIGHT_CURRENT_ZC      1226
#define IDC_EDIT_HEIGHT_CURRENT_A       1227
#define IDC_EDIT_HEIGHT_CURRENT_B       1228
#define IDC_EDIT_HEIGHT_CURRENT_C       1229
#define IDC_EDIT_HEIGHT_CURRENT_D       1230
#define IDC_EDIT_HEIGHT_X_POS           1231
#define IDC_EDIT_HEIGHT_Y_POS           1232
#define IDC_EDIT_HEIGHT_ZA_POS          1233
#define IDC_EDIT_HEIGHT_ZB_POS          1234
#define IDC_EDIT_HEIGHT_ZC_POS          1235
#define IDC_EDIT_HEIGHT_SENSOR_X_POS    1236
#define IDC_EDIT_HEIGHT_SENSOR_Y_POS    1237
#define IDC_EDIT_HEIGHT_SENSOR_ZA_POS   1238
#define IDC_EDIT_HEIGHT_CAMERA_X_POS    1239
#define IDC_EDIT_HEIGHT_CAMERA_Y_POS    1240
#define IDC_EDIT_HEIGHT_CAMERA_ZA_POS   1241
#define IDC_EDIT_HEIGHT_VEL             1242
#define IDC_EDIT_HEIGHT_ACC             1243
#define IDC_EDIT_HEIGHT_PITCH           1244
#define IDC_EDIT_HEIGHT_GLUE_VOL        1245
#define IDC_BTN_HEIGHT_HOME             1246
#define IDC_BTN_HEIGHT_SAVE_POS         1247
#define IDC_BTN_HEIGHT_CALIBRATION      1248
#define IDC_BTN_HEIGHT_MEASURE_ONE      1249
#define IDC_BTN_HEIGHT_MEASURE_TWO      1250
#define IDC_BTN_HEIGHT_MEASURE_THREE    1251
#define IDC_BTN_HEIGHT_CAMERA_POS       1252
#define IDC_BTN_HEIGHT_ZSAFE_POS        1253
#define IDC_BTN_HEIGHT_SWITCH           1254
#define IDC_BTN_HEIGHT_POS              1255
#define IDC_EDIT_HEIGHT_CURRENT_VALUE   1256
#define IDC_EDIT_HEIGHT_STANDARD_VALUE  1257
#define IDC_EDIT_HEIGHT_HEIGHT_CURRENT_VALUE 1258
#define IDC_EDIT_HEIGHT_HEIGHT_STANDARD_VALUE 1259
#define IDC_EDIT_HEIGHT_NUMBER          1260
#define IDC_BTN_NEEDLE_X_NEG            1300
#define IDC_BTN_NEEDLE_X_POS            1301
#define IDC_BTN_NEEDLE_Y_NEG            1302
#define IDC_BTN_NEEDLE_Y_POS            1303
#define IDC_BTN_NEEDLE_ZA_NEG           1304
#define IDC_BTN_NEEDLE_ZA_POS           1305
#define IDC_BTN_NEEDLE_ZB_NEG           1306
#define IDC_BTN_NEEDLE_ZB_POS           1307
#define IDC_BTN_NEEDLE_ZC_NEG           1308
#define IDC_BTN_NEEDLE_ZC_POS           1309
#define IDC_BTN_NEEDLE_A_NEG            1310
#define IDC_BTN_NEEDLE_A_POS            1311
#define IDC_BTN_NEEDLE_B_NEG            1312
#define IDC_BTN_NEEDLE_B_POS            1313
#define IDC_BTN_NEEDLE_C_NEG            1314
#define IDC_BTN_NEEDLE_C_POS            1315
#define IDC_BTN_NEEDLE_D_NEG            1316
#define IDC_BTN_NEEDLE_D_POS            1317
#define IDC_SLIDER_NEEDLE_SPEED         1318
#define IDC_EDIT_NEEDLE_SPEED           1319
#define IDC_SLIDER_NEEDLE_ADJUST_SPEED  1320
#define IDC_EDIT_NEEDLE_ADJUST_SPEED    1321
#define IDC_EDIT_NEEDLE_CURRENT_POS_X   1322
#define IDC_EDIT_NEEDLE_CURRENT_POS_Y   1323
#define IDC_EDIT_NEEDLE_CURRENT_POS_Z   1324
#define IDC_EDIT_NEEDLE_CURRENT_POS_ZA  1325
#define IDC_EDIT_NEEDLE_CURRENT_POS_ZB  1326
#define IDC_EDIT_NEEDLE_CURRENT_POS_ZC  1327
#define IDC_EDIT_NEEDLE_CURRENT_POS_A   1328
#define IDC_EDIT_NEEDLE_CURRENT_POS_B   1329
#define IDC_EDIT_NEEDLE_CURRENT_POS_C   1330
#define IDC_EDIT_NEEDLE_CURRENT_POS_D   1331
#define IDC_EDIT_NEEDLE_ENC_POS_X       1332
#define IDC_EDIT_NEEDLE_ENC_POS_Y       1333
#define IDC_EDIT_NEEDLE_ENC_POS_ZA      1334
#define IDC_EDIT_NEEDLE_ENC_POS_ZB      1335
#define IDC_EDIT_NEEDLE_ENC_POS_ZC      1336
#define IDC_EDIT_NEEDLE_ENC_POS_A       1337
#define IDC_EDIT_NEEDLE_ENC_POS_B       1338
#define IDC_EDIT_NEEDLE_ENC_POS_C       1339
#define IDC_EDIT_NEEDLE_ENC_POS_D       1340
#define IDC_EDIT_NEEDLE_X_POS           1341
#define IDC_EDIT_NEEDLE_Y_POS           1342
#define IDC_EDIT_NEEDLE_Z_POS           1343
#define IDC_EDIT_NEEDLE_VEL             1344
#define IDC_EDIT_NEEDLE_ACC             1345
#define IDC_EDIT_NEEDLE_PITCH           1346
#define IDC_EDIT_NEEDLE_CLEAN_PITCH     1347
#define IDC_BTN_NEEDLE_ADJUST_MOTOR_ZERO 1348
#define IDC_BTN_NEEDLE_ONE_LABEL_POS    1349
#define IDC_BTN_NEEDLE_TWO_LABEL_POS    1350
#define IDC_BTN_NEEDLE_THREE_LABEL_POS  1351
#define IDC_STATIC_NEEDLE_PICTURE       1352
#define IDC_BTN_NEEDLE_GAP              1353
#define IDC_BTN_NEEDLE_LABEL            1354
#define IDC_BTN_NEEDLE_ADJUST_MOTOR_RESET 1355
#define IDC_BTN_NEEDLE_ADJUST_NEEDLE    1356
#define IDC_BTN_NEEDLE_ADJUST_CLEAN     1357
#define IDC_BTN_NEEDLE_CAMERA_LABEL_POS 1358
#define IDC_BTN_NEEDLE_HEIGHT_LABEL_POS 1359
#define IDC_EDIT_NEEDLE_HIGHT_VALUE     1360
#define IDC_BTN_NEEDLE_HEIGHT_POS       1361
#define IDC_EDIT_LX_VALVEONE            1362
#define IDC_EDIT_LX_VALVETWO            1363
#define IDC_EDIT_LX_VALVETHREE          1364
#define IDC_EDIT_LY_VALVEONE            1365
#define IDC_EDIT_LY_VALVETWO            1366
#define IDC_EDIT_LY_VALVETHREE          1367
#define IDC_EDIT_OFFSET2X               1368
#define IDC_EDIT_OFFSET2Y               1369
#define IDC_EDIT_OFFSET3X               1370
#define IDC_EDIT_OFFSET3Y               1371
#define IDC_EDIT_CONVERTPOS_FA2         1372
#define IDC_EDIT_CONVERTPOS_FA3         1373
#define IDC_BTN_ALIGN_X_NEG             1500
#define IDC_BTN_ALIGN_X_POS             1501
#define IDC_BTN_ALIGN_Y_NEG             1502
#define IDC_BTN_ALIGN_Y_POS             1503
#define IDC_BTN_ALIGN_ZA_NEG            1504
#define IDC_BTN_ALIGN_ZA_POS            1505
#define IDC_SLIDER_ALIGN_SPEED          1506
#define IDC_EDIT_ALIGN_SPEED            1507
#define IDC_EDIT_ALIGN_X_POS            1508
#define IDC_EDIT_ALIGN_Y_POS            1509
#define IDC_EDIT_ALIGN_ZA_POS           1510
#define IDC_EDIT_ALIGN_NEEDLE_HEIGHT    1511
#define IDC_EDIT_ALIGN_NEEDLE_PROMPT    1512
#define IDC_BTN_ALIGN_NEEDLE_NEXT       1513
#define IDC_STATIC_ALIGN_PICTURE_CONTROL 1514
#define IDC_EDIT_ALIGN_HEIGHT_CURRENT_VALUE 1515
#define IDC_BTN_PLC0                    1600
#define IDC_BTN_PLC1                    1601
#define IDC_BTN_PLC2                    1602
#define IDC_BTN_PLC3                    1603
#define IDC_BTN_PLC4                    1604
#define IDC_BTN_PLC5                    1605
#define IDC_BTN_PLC6                    1606
#define IDC_BTN_PLC7                    1607
#define IDC_BTN_PLC8                    1608
#define IDC_BTN_PLC9                    1609
#define IDC_BTN_PLC10                   1610
#define IDC_BTN_PLC11                   1611
#define IDC_BTN_PLC12                   1612
#define IDC_BTN_PLC13                   1613
#define IDC_BTN_PLC14                   1614
#define IDC_BTN_PLC15                   1615
#define IDC_BTN_PLC16                   1616
#define IDC_BTN_PLC17                   1617
#define IDC_BTN_PLC18                   1618
#define IDC_BTN_PLC19                   1619
#define IDC_BTN_PLC20                   1620
#define IDC_BTN_PLC21                   1621
#define IDC_BTN_PLC22                   1622
#define IDC_BTN_PLC23                   1623
#define IDC_BTN_PLC24                   1624
#define IDC_BTN_PLC25                   1625
#define IDC_BTN_PLC26                   1626
#define IDC_BTN_PLC27                   1627
#define IDC_BTN_PLC28                   1628
#define IDC_BTN_PLC29                   1629
#define IDC_BTN_PLC30                   1630
#define IDC_BTN_PLC31                   1631
#define IDC_BTN_PLC32                   1632
#define IDC_BTN_PLC33                   1633
#define IDC_BTN_PLC34                   1634
#define IDC_BTN_PLC35                   1635
#define IDC_BTN_PLC36                   1636
#define IDC_BTN_PLC37                   1637
#define IDC_BTN_PLC38                   1638
#define IDC_BTN_PLC39                   1639
#define IDC_EDIT_PLC_LOAD_VEL           1640
#define IDC_EDIT_PLC_UNLOAD_VEL         1641
#define IDC_EDIT_PLC_LOAD_MAG_NUM       1642
#define IDC_EDIT_PLC_LOAD_MAG_SPACE     1643
#define IDC_EDIT_PLC_UNLOAD_MAG_NUM     1644
#define IDC_EDIT_PLC_UNLOAD_MAG_SPACE   1645
#define IDC_EDIT_PLC_DISPENSE_VEL       1646
#define IDC_EDIT_PLC_FILL_VEL           1647
#define IDC_EDIT_PLC_FILL_DISTANCE      1648
#define IDC_SAVE                        1649
#define IDC_CANCEL                      1650
#define IDC_BTN_PLC_MANUAL_LOAD         1651
#define IDC_BTN_PLC_MANUAL_UNLOAD       1652
#define IDC_BTN_PLC_PREHEAT             1653
#define IDC_BTN_PLC_HEAT                1654
#define IDC_CHECK_PLC_PREHEAT           1655
#define IDC_CHECK_PLC_HEAT              1656
#define IDC_CHECK_PLC_PREHEAT_RESET     1657
#define IDC_CHECK_PLC_HEAT_RESET        1658
#define IDC_EDIT_PLC_PREHEAT_SETTING    1659
#define IDC_EDIT_PLC_HEAT_SETTING       1660
#define IDC_EDIT_PLC_PREHEAT_TEMP       1661
#define IDC_EDIT_PLC_HEAT_TEMP          1662
#define IDC_EDIT_PLC_PUSH_COUNT         1663
#define IDC_EDIT_BLOB_THRESHOLD         1700
#define IDC_EDIT_BLOB_SCALE             1701
#define IDC_EDIT_BLOB_POS_X             1702
#define IDC_EDIT_BLOB_POS_Y             1703
#define IDC_EDIT_BLOB_PARAM_POS_X       1704
#define IDC_EDIT_BLOB_PARAM_POS_Y       1705
#define IDC_EDIT_BLOB_PARAM_MIN_LENGTH  1706
#define IDC_EDIT_BLOB_PARAM_MAX_LENGTH  1707
#define IDC_EDIT_BLOB_PARAM_MIN_WIDTH   1708
#define IDC_EDIT_BLOB_PARAM_MAX_WIDTH   1709
#define IDC_EDIT_BLOB_PARAM_MIN_AREA    1710
#define IDC_EDIT_BLOB_PARAM_MAX_AREA    1711
#define IDC_EDIT_BLOB_ROI_LEFT          1712
#define IDC_EDIT_BLOB_ROI_TOP           1713
#define IDC_EDIT_BLOB_ROI_RIGHT         1714
#define IDC_EDIT_BLOB_ROI_BOTTOM        1715
#define IDC_EDIT_BLOB_CURRENT_POS_X     1716
#define IDC_EDIT_BLOB_CURRENT_POS_Y     1718
#define IDC_EDIT_BLOB_CURRENT_POS_Z     1719
#define IDC_EDIT_BLOB_IMAGE_POS_X       1720
#define IDC_EDIT_BLOB_IMAGE_POS_Y       1721
#define IDC_EDIT_BLOB_IMAGE_POS_Z       1722
#define IDC_STATIC_BLOB_PIC             1723
#define IDC_COMBO_BLOB                  1724
#define IDC_BTN_BLOB_SAVE_ROI           1725
#define IDC_BTN_BLOB_COM_SCALE          1726
#define IDC_BTN_BLOB_NEW_PIC            1727
#define IDC_BTN_BLOB_MOVE_GRABPOS       1728
#define IDC_BTN_BLOB_SAVE_POS           1729
#define IDC_BTN_BLOB_SHOW_ROI           1730
#define IDC_BTN_BLOB_CLEAR_ROI          1731
#define IDC_BTN_BLOB_SAVE_CENTER        1732
#define IDC_BTN_BLOB_TEST               1733
#define IDC_EDIT_MARK_SCALE             1800
#define IDC_EDIT_MARK_ANGLE             1801
#define IDC_EDIT_MARK_ACCEPTANCE        1802
#define IDC_EDIT_MARK_CURRENT_X         1804
#define IDC_EDIT_MARK_CURRENT_Y         1805
#define IDC_EDIT_MARK_CURRENT_Z         1806
#define IDC_EDIT_MARK_IMAGE_POS_X       1807
#define IDC_EDIT_MARK_IMAGE_POS_Y       1808
#define IDC_EDIT_MARK_IMAGE_POS_Z       1809
#define IDC_EDIT_MARK_LEARN_WIN_LEFT    1810
#define IDC_EDIT_MARK_LEARN_WIN_TOP     1811
#define IDC_EDIT_MARK_LEARN_WIN_RIGHT   1812
#define IDC_EDIT_MARK_LEARN_WIN_BOTTOM  1813
#define IDC_EDIT_MARK_ROI_LEFT          1814
#define IDC_EDIT_MARK_ROI_RIGHT         1815
#define IDC_EDIT_MARK_ROI_TOP           1816
#define IDC_EDIT_MARK_ROI_BOTTOM        1817
#define IDC_EDIT_MARK_RESULT_SCORE      1818
#define IDC_EDIT_MARK_RESULT_ANGLE      1819
#define IDC_EDIT_MARK_RESULT_CENTER_X   1820
#define IDC_EDIT_MARK_RESULT_CENTER_Y   1821
#define IDC_STATIC_MARK_PIC             1822
#define IDC_COMBO_MARK                  1823
#define IDC_BTN_MARK_SCALE              1824
#define IDC_BTN_MARK_GRABPOS            1825
#define IDC_BTN_MARK_NEWPIC             1826
#define IDC_BTN_MARK_SAVE_ROI           1827
#define IDC_BTN_MARK_TEST               1828
#define IDC_BTN_MARK_SAVE_LEARN_WIN     1829
#define IDC_BTN_MARK_SHOW_LEARN_WIN     1830
#define IDC_BTN_MARK_SAVE_MODEL         1831
#define IDC_BTN_MARK_SEARCH             1832
#define IDC_BTN_MARK_CLEAR              1833
#define IDC_BTN_MARK_MOVE_CENTER        1834
#define IDC_BTN_MARK_SAVE_CENTER        1835
#define IDC_COMBO_MARK_SELECT           1836
#define IDC_SLIDER_MARK_EXPOSURE_TIME   1837
#define IDC_EDIT_MARK_EXPOSURE_TIME     1838
#define IDC_SLIDER_MARK_GAIN            1839
#define IDC_EDIT_MARK_GAIN              1840
#define IDC_EDIT_MARK_CALIBRATION_A     1841
#define IDC_EDIT_MARK_CALIBRATION_B     1842
#define IDC_EDIT_MARK_CALIBRATION_C     1843
#define IDC_EDIT_MARK_CALIBRATION_D     1844
#define IDC_COMBO_MARK_TRACK_SELECT     1845
#define IDC_EDIT_PATTERN_SCALE          1900
#define IDC_EDIT_PATTERN_ANGLE          1901
#define IDC_EDIT_PATTERN_ACCEPTANCE     1902
#define IDC_EDIT_PATTERN_POS_Y          1903
#define IDC_EDIT_PATTERN_CURRENT_POS_X  1904
#define IDC_EDIT_PATTERN_CURRENT_POS_Y  1905
#define IDC_EDIT_PATTERN_CURRENT_POS_Z  1906
#define IDC_EDIT_PATTERN_IMAGE_POS_X    1907
#define IDC_EDIT_PATTERN_IMAGE_POS_Y    1908
#define IDC_EDIT_PATTERN_IMAGE_POS_Z    1909
#define IDC_EDIT_PATTERN_LEARNWIN_LEFT  1910
#define IDC_EDIT_PATTERN_LEARNWIN_RIGHT 1911
#define IDC_EDIT_PATTERN_LEARNWIN_TOP   1912
#define IDC_EDIT_PATTERN_LEARNWIN_BOTTOM 1913
#define IDC_EDIT_PATTERN_ROI_LEFT       1914
#define IDC_EDIT_PATTERN_ROI_RIGHT      1915
#define IDC_EDIT_PATTERN_ROI_TOP        1916
#define IDC_EDIT_PATTERN_ROI_BOTTOM     1917
#define IDC_EDIT_PATTERN_RESULT_SCORE   1918
#define IDC_EDIT_PATTERN_RESULT_ANGLE   1919
#define IDC_EDIT_PATTERN_RESULT_CENTER_X 1920
#define IDC_EDIT_PATTERN_RESULT_CENTER_Y 1921
#define IDC_STATIC_PATTERN              1922
#define IDC_BTN_PATTERN_SCALE           1923
#define IDC_BTN_PATTERN_NEWPIC          1924
#define IDC_BTN_PATTERN_FIRST_IMAGE_POS 1925
#define IDC_BTN_PATTERN_NEXT_IMAGE_POS  1926
#define IDC_BTN_PATTERN_SAVE_ROI        1927
#define IDC_BTN_PATTERN_SHOW_ROI        1928
#define IDC_BTN_PATTERN_SAVE_LEARN_WIN  1929
#define IDC_BTN_PATTERN_SHOW_LEARN_WIN  1930
#define IDC_BTN_PATTERN_SAVE_MODEL      1931
#define IDC_BTN_PATTERN_SEARCH          1932
#define IDC_BTN_PATTERN_MOVE_CENTER     1933
#define IDC_BTN_PATTERN_CLEAR           1934
#define IDC_EDIT_FACTORY_PARAM_MAX_POS  2000
#define IDC_EDIT_FACTORY_PARAM_MIN_POS  2001
#define IDC_EDIT_FACTORY_PARAM_VEL      2002
#define IDC_EDIT_FACTORY_PARAM_ACC      2003
#define IDC_EDIT_FACTORY_PARAM_SCALE    2004
#define IDC_EDIT_FACTORY_PARAM_MAX_VEL  2005
#define IDC_EDIT_FACTORY_PARAM_MAX_HOME_VEL 2006
#define IDC_EDIT_FACTORY_PARAM_MIN_HOME_VEL 2007
#define IDC_EDIT_FACTORY_PARAM_HOME_ACC 2008
#define IDC_COMBO_FACTORY_PARAM_MOTOR   2009
#define IDC_EDIT_FACTORY_PARAM_JERK     2010
#define IDC_COMBO_FACTORY_PARAM_VEL_TYPE 2011
#define IDC_EDIT_FACTORY_PARAM_DEC      2012
#define IDC_EDIT_FACTORY_PARAM_STARTVEL 2013
#define IDC_BTN_RCD_X_NEG               2100
#define IDC_BTN_RCD_X_POS               2101
#define IDC_BTN_RCD_Y_NEG               2102
#define IDC_BTN_RCD_Y_POS               2103
#define IDC_BTN_RCD_Z_NEG               2104
#define IDC_BTN_RCD_Z_POS               2105
#define IDC_RCD_SLIDER_SPEED            2106
#define IDC_EDIT_RCD_MOTION             2107
#define IDC_EDIT_RCD_PROMPT             2108
#define IDC_BTN_RCD_NEXT                2109
#define IDC_STATIC_RCD_PICTURE          2110
#define IDC_EDIT_MACHINE_CODE           2200
#define IDC_EDIT_REGISTER_CODE_TYPE     2201
#define IDC_EDIT_VALIDITY_PERIOD        2202
#define IDC_EDIT_REMAINING_TIME         2203
#define IDC_EDIT_REGISTER_CODE          2204
#define IDC_CHECK_PLC_INPUT1            2210
#define IDC_CHECK_PLC_INPUT2            2211
#define IDC_BTN_PAD_DETECT_LIGHT        2212
#define IDC_BTN_PAD_DETECT_ROTATE       2213
#define IDC_BTN_PAD_DETECT_X_NEG        2283
#define IDC_BTN_PAD_DETECT_X_POS        2284
#define IDC_BTN_PAD_DETECT_Y_NEG        2285
#define IDC_BTN_PAD_DETECT_Y_POS        2286
#define IDC_BTN_PAD_DETECT_Z_NEG        2287
#define IDC_BTN_PAD_DETECT_Z_POS        2288
#define IDC_SLIDER_PAD_DETECT_SPEED     2289
#define IDC_EDIT_PAD_DETECT_SPEED       2290
#define IDC_PAMA33                      2290
#define IDC_EDIT_LOAD_POS1              2290
#define IDC_EDIT_Z_SAFEPOS              2290
#define IDC_PAMA34                      2291
#define IDC_PAMA35                      2292
#define IDC_BTN_SET_Z_SAFE_POS          2293
#define IDC_BTN_MOV_LASER               2294
#define IDC_BTN_SAVE_LASER              2295
#define IDC_CHK_USE_LASER               2296
#define IDC_BTN_SAVE_LASER2             2297
#define IDC_BTN_SAVE_LASER_VAL          2297
#define IDC_BTN_SAVE_LASER_VAL2         2298
#define IDC_BTN_SAVE_ADJUST_VAL         2298
#define IDC_BTN_BLOCKCLEAN              2299
#define IDC_BTN_MANUAL_LOAD             2299
#define IDC_BUTTON_X_NEG                2300
#define IDC_BUTTON_X_POS                2301
#define IDC_BUTTON_Y_NEG                2302
#define IDC_BUTTON_Y_POS                2303
#define IDC_BUTTON_ZA_NEG               2304
#define IDC_BUTTON_ZA_POS               2305
#define IDC_BUTTON_ZB_NEG               2306
#define IDC_BUTTON_ZB_POS               2307
#define IDC_BUTTON_ZC_NEG               2308
#define IDC_BUTTON_ZC_POS               2309
#define IDC_SLIDER_SPEED                2310
#define IDC_EDIT_KEYCTRL                2311
#define IDC_PX1                         2312
#define IDC_PY1                         2313
#define IDC_PZA1                        2314
#define IDC_PZB1                        2315
#define IDC_PZC1                        2316
#define IDC_PX2                         2317
#define IDC_PY2                         2318
#define IDC_PZA2                        2319
#define IDC_PZB2                        2320
#define IDC_PZC2                        2321
#define IDC_PX3                         2322
#define IDC_PY3                         2323
#define IDC_PZA3                        2324
#define IDC_PZB3                        2325
#define IDC_PZC3                        2326
#define IDC_PX4                         2327
#define IDC_PY4                         2328
#define IDC_PZA4                        2329
#define IDC_PZB4                        2330
#define IDC_PZC4                        2331
#define IDC_PX5                         2332
#define IDC_PY5                         2333
#define IDC_PZA5                        2334
#define IDC_PX6                         2335
#define IDC_PY6                         2336
#define IDC_PZA6                        2337
#define IDC_PX8                         2338
#define IDC_ZFOCUSA                     2338
#define IDC_PY8                         2339
#define IDC_PZA8                        2340
#define IDC_PX7                         2341
#define IDC_PY7                         2342
#define IDC_PZA7                        2343
#define IDC_SAVE_DISPENSING_POS         2344
#define IDC_MOVE_DISPENSING_POS         2345
#define IDC_BTN_SAVE_CURRENT_DISP_POS   2346
#define IDC_BTN_SAVE_MODIFY_DISP_POS    2347
#define IDC_BTN_ALIGN_NEEDLE            2348
#define IDC_MOVE_ADJUST_NEEDLE          2349
#define IDC_MOVE_ADJUST_CLEAN           2350
#define IDC_SAVE_CLEAN_POS              2351
#define IDC_MOVE_CLEAN_POS              2352
#define IDC_CLEAN                       2353
#define IDC_SAVE_TEST_DISP_POS          2354
#define IDC_MOVE_TEST_DISP_POS          2355
#define IDC_TEST_DISP                   2356
#define IDC_BTN_MOVE_DISCHARGE_POS      2357
#define IDC_BTN_SAVE_DISCHARGE_POS      2358
#define IDC_BTN_DISCHARGE_GLUE          2359
#define IDC_BTN_DEFOAM                  2360
#define IDC_MOVE_START_IMAGE_POS        2361
#define IDC_EDIT_CUR_LASER_VAL          2362
#define IDC_MOVE_END_IMAGE_POS          2363
#define IDC_BTN_MOVE_SLOT_DETECT_POS    2364
#define IDC_BTN_SAVE_SLOT_DETECT_POS    2365
#define IDC_COMBO_TEST_INDEX            2366
#define IDC_SET_TEST_DISPENSE           2367
#define IDC_SINGLE_TEST_DISPENSE        2368
#define IDC_COMBO_CTRL_HEIGHT_INDEX     2369
#define IDC_BTN_CTRL_MOVETO_HEIGHT_POS  2370
#define IDC_BTN_CTRL_SET_HEIGHT_POS     2371
#define IDC_BTN_CTRL_MEASURE_HEIGHT     2372
#define IDC_EDIT_CTRL_HEIGHT_NUMBER     2373
#define IDC_DISP_Z_POS                  2374
#define IDC_DISP_Z_POS_FEED             2375
#define IDC_BTN_DEBUG_HEIGHT_X_NEG      2400
#define IDC_BTN_DEBUG_HEIGHT_X_POS      2401
#define IDC_BTN_DEBUG_HEIGHT_Y_NEG      2402
#define IDC_BTN_DEBUG_HEIGHT_Y_POS      2403
#define IDC_BTN_DEBUG_HEIGHT_Z_NEG      2404
#define IDC_BTN_DEBUG_HEIGHT_Z_POS      2405
#define IDC_SLIDER_DEBUG_HEIGHT_SPEED   2406
#define IDC_EDIT_DEBUG_HEIGHT_SPEED     2407
#define IDC_BTN_DEBUG_HEIGHT_NEXT       2408
#define IDC_BTN_DEBUG_HEIGHT_SWITCH     2409
#define IDC_EDIT_DEBUG_HEIGHT_STANDARD_VALUE 2410
#define IDC_EDIT_DEBUG_HEIGHT_CURRENT_VALUE 2411
#define IDC_EDIT_INFO_CURRENT_POS_X     2500
#define IDC_EDIT_INFO_CURRENT_POS_Y     2501
#define IDC_EDIT_INFO_CURRENT_POS_ZA    2502
#define IDC_EDIT_INFO_CURRENT_POS_ZB    2503
#define IDC_EDIT_INFO_CURRENT_POS_ZC    2504
#define IDC_EDIT_INFO_CURRENT_POS_FA    2505
#define IDC_EDIT_INFO_CURRENT_POS_FB    2506
#define IDC_EDIT_INFO_CURRENT_POS_FC    2507
#define IDC_EDIT_INFO_PRODUCT_COMPLETED 2508
#define IDC_EDIT_INFO_TOTAL_TIME        2509
#define IDC_EDIT_INFO_STANDBY_TIME      2510
#define IDC_EDIT_INFO_RUN_TIME          2511
#define IDC_EDIT_INFO_ST                2512
#define IDC_EDIT_INFO_UPH               2513
#define IDC_BTN_INFO_RESET              2514
#define IDC_BTN_INFO_CLEAR_ERROR        2515
#define IDC_BTN_INFO_CLEAR_CAPACITY     2516
#define IDC_STATIC_INFO_ERROR           2517
#define IDC_STATIC_INFO_STS             2518
#define IDC_BTN_INFO_DEBUG              2519
#define IDC_STATIC_INFO_REGISTER        2520
#define IDC_BTN_INFO_MOVETO_CLEAN_POS   2521
#define IDC_BTN_INFO_MOVETO_DISCHARGE_POS 2522
#define IDC_BTN_INFO_CLEAR_SLOT         2523
#define IDC_EDIT_INFO_GLUE_A            2524
#define IDC_EDIT_INFO_GLUE_B            2525
#define IDC_EDIT_INFO_GLUE_C            2526
#define IDC_BTN_INFO_CLEAR_DETECT       2527
#define IDC_BUTTON1                     2541
#define IDC_BTN_NEEDLE_HEIGHT_ZERO      2541
#define IDC_BTN_AUTO_NEEDLE_SEARCH      2541
#define IDC_BtnModifyDischarge          2541
#define IDC_BTN_SETPOS_ZC_NEG           2541
#define IDC_BTN_ZTOFOCUS                2541
#define IDC_BTN_LARGER                  2541
#define IDC_BTN_FIRSTPIXSEL_SAVE        2541
#define IDC_BTN_DETECT_BASEPOINT_NEXT   2541
#define asd                             2541
#define IDC_BTN_HEIGHT_LASERSAVE        2541
#define IDC_BTN_SAVEALL                 2541
#define IDC_BTN_NEEDLEGAP               2541
#define IDC_BTN_FOCUS_TWO               2541
#define IDC_BTN_FOCUS_THREE             2541
#define IDC_BTN_TEST                    2541
#define IDC_BTN_INFO_ARRANGE_TIME       2541
#define IDC_BTN_UNION_SAVE_ALL          2541
#define IDC_BTN_PUTCROSS                2541
#define IDC_BTN_FINDBLOB                2541
#define IDC_BTN_TARGETPOS               2541
#define IDC_BTN_APPLY                   2541
#define IDC_BTN_VALVEHEATCTRL           2541
#define IDC_BUTTON_UDP_RESET            2541
#define IDC_BTN_SEND                    2541
#define IDC_BTN_LINEBACK                2541
#define IDC_EDIT_MULTI_ROW_NUMBER       2542
#define IDC_BTN_SETPOS_ZB_NEG           2542
#define IDC_EDIT_MULTI_COLUMN_NUMBER    2543
#define IDC_BTN_SETPOS_ZC_POS           2543
#define IDC_EDIT_MULTI_ROW_DISTANCE     2544
#define IDC_BTN_SETPOS_ZB_POS           2544
#define IDC_EDIT_MULTI_COLUMN_DISTANCE  2545
#define IDC_RADIO1                      2546
#define IDC_BUTTON8                     2546
#define IDC_BtnModifyClean              2547
#define IDC_BTN_SAVE_MODIFY_FOCUS       2548
#define IDC_BTN_SAVE_CURRENT_FOCUS_POS  2549
#define IDC_BTN_MOVE_FOCUS_POS          2550
#define IDC_BTN_NEEDLE_ONE              2551
#define IDC_BTN_NEEDLE_TWO              2552
#define IDC_BUTTON2                     2552
#define IDC_BTN_SMALLER                 2552
#define IDC_BTN_ZALITTLENEG             2552
#define IDC_BTN_SAVE_TESTZ_EACH         2552
#define IDC_BTN_NEEDLE_THIRD            2553
#define IDC_FIRST_PIXSEL_X              2553
#define IDC_BTN_CEMERA                  2554
#define IDC_EDIT2                       2554
#define IDC_FIRST_PIXSEL_Y              2554
#define IDC_EDIT_NEEDLE_ANGLE           2554
#define IDC_EDIT_COMPOSE_THIRDY         2554
#define IDC_EDIT_INFO_REMAINING_TIME    2554
#define IDC_EDIT_GLUE_REAL              2554
#define IDC_EDIT_SCALEB                 2554
#define IDC_EDIT_FACTORY_PARAM_MOTORC   2554
#define IDC_EDIT_TEMPTWO                2554
#define IDC_EDIT_REALTB                 2554
#define IDC_EDIT_MARKCAMNO              2554
#define IDC_BTN_LASER                   2555
#define IDC_STATIC_DETECT_BASEPOINT_PICTURE 2555
#define IDC_BTN_LASER_DATAREAD          2556
#define IDC_EDIT1                       2556
#define IDC_EDIT_DETECT_BASEPOINT_PROMPT 2556
#define IDC_EDIT_HEIGHT_PROMPT          2556
#define IDC_EDIT_PLC_TRANSIT_SPEED      2556
#define IDC_EDIT_MIN_DISTANCE           2556
#define IDC_EDIT_NEEDLE_ACCEPTANCE      2556
#define IDC_EDIT_COMPOSE_SECONDY        2556
#define IDC_EDIT_GLUE_SETTING           2556
#define IDC_EDIT_SCALEA                 2556
#define IDC_EDIT_ZOFFSET_ALL            2556
#define IDC_EDIT_FACTORY_PARAM_MOTORA   2556
#define IDC_EDIT_VALVE_DIAMOND          2556
#define IDC_EDIT_VALVE_DIAMETER         2556
#define IDC_EDIT_ALL_FULL_HEIGHT        2556
#define IDC_EDIT_TEMPONE                2556
#define IDC_EDIT_REALTA                 2556
#define IDC_EDIT_URL                    2556
#define IDC_EDIT_MATERIALCODE           2556
#define IDC_CHECK_PLC_INBOX_DETECT      2557
#define IDC_CHECK2                      2558
#define IDC_CHECK_PLC_OUTBOX_DETECT     2558
#define IDC_CHK_CLEAN                   2558
#define IDC_CHECK_HEAT_ENABLE           2558
#define IDC_CHECK_HEATB                 2558
#define IDC_BTN_ZALITTLEPOS             2559
#define IDC_CHECK_HEAT_ENABLE2          2559
#define IDC_SLIDER1                     2560
#define IDC_SLIDER_NEEDLE_EXPOSURE_TIME 2560
#define IDC_SLIDER_NEEDLE_GAIN          2561
#define IDC_STATIC_NEEDLEONE            2562
#define IDC_BUTTON3                     2563
#define IDC_BTN_LASERPOS_MODIFY         2563
#define IDC_BTN_A                       2563
#define IDC_BTN_HEATB                   2563
#define IDC_BTN_LASER_LABLE             2564
#define IDC_PIC_CONTATOR                2565
#define IDC_STATIC_VALVE_YOFFSET        2566
#define IDC_EDIT_COMPOSE_SECONDX        2567
#define IDC_EDIT4                       2568
#define IDC_EDIT_COMPOSE_THIRDX         2568
#define IDC_EDIT_FACTORY_PARAM_DIAMOND  2568
#define IDC_EDIT_INFO_BARCODE           2568
#define IDC_EDIT_SETA                   2568
#define IDC_SLIDER2                     2569
#define IDC_CHECK_INFO_ENABLE_ARRANGE   2570
#define IDC_COMBO1                      2571
#define IDC_COMBO_LOG                   2571
#define IDC_COMBO_IMGSELECT             2571
#define IDC_CHECK_AUTO_DEFOAM           2572
#define IDC_EDIT_DEFOAM_TIME            2573
#define IDC_CHECK1                      2574
#define IDC_CHECK_PLC_TEMP_DETECT       2574
#define IDC_CHECK_TEMP_JUDGE            2574
#define IDC_CHECK_SAFE_SENSOR           2574
#define IDC_CHECK_HEATA                 2574
#define IDC_BTN_STOP_DISCHARGE          2575
#define IDC_EDIT_TEMP_ERROR             2576
#define IDC_EDIT3                       2577
#define IDC_EDIT_GASKETRING_LIFE        2577
#define IDC_EDIT_VALVE_REMAIN           2577
#define IDC_EDIT_FACTORY_PARAM_         2577
#define IDC_EDIT_FACTORY_PARAM_LOGOUT   2577
#define IDC_EDIT_REALTC                 2577
#define IDC_EDIT_NEEDLECAMNO            2577
#define IDC_BTN_ZOFFSET_APPLY           2578
#define IDC_BTN_VALVE_UPDATE            2579
#define IDC_EDIT5                       2580
#define IDC_EDIT_VALVECLEAN_TIME        2580
#define IDC_EDIT_SETB                   2580
#define IDC_RADIO2                      2581
#define IDC_EDIT6                       2582
#define IDC_EDIT_REMIND_CLEAN           2582
#define IDC_EDIT_HEIGHT_COMPMAX         2582
#define IDC_EDIT_SETC                   2582
#define IDC_CHECK3                      2583
#define IDC_CHECK_MES_OFFLINE           2583
#define IDC_CHECK_HEATC                 2583
#define IDC_STATIC_STEPONE              2584
#define IDC_STATIC_STEPTWO              2585
#define IDC_STATIC_STEPTHREE            2586
#define IDC_STATIC_STEPFOUR             2587
#define IDC_BTN_B                       2588
#define IDC_BTN_C                       2589
#define IDC_BUTTON7                     2591
#define IDC_BTN_ADJUSTC                 2591
#define IDC_STATIC_DOWMCAM              2592
#define IDC_EDIT_CONTACT_FREQ           2595
#define IDC_EDIT_CONTACT_ERRPERMIT      2596
#define IDC_CHECK4                      2597
#define IDC_CHECK_NEEDLECHECK           2597
#define IDC_CHECK_ADJUSTA               2597
#define IDC_BUTTON_PRODUCTIVITYR        2598
#define IDC_BTN_HEATA                   2599
#define IDC_CHECK_INPUT0                2600
#define IDC_BTN_HEATC                   2600
#define IDC_CHECK_INPUT1                2601
#define IDC_BTN_ADJUSTA                 2601
#define IDC_CHECK_INPUT2                2602
#define IDC_BTN_ADJUSTB                 2602
#define IDC_CHECK_INPUT3                2603
#define IDC_CHECK_ADJUSTB               2603
#define IDC_CHECK_INPUT4                2604
#define IDC_CHECK_ADJUSTC               2604
#define IDC_CHECK_INPUT5                2605
#define IDC_EDIT_UDP_PORT               2605
#define IDC_CHECK_INPUT6                2606
#define IDC_CHECK_INPUT7                2607
#define IDC_IPADDRESS_DUP               2607
#define IDC_CHECK_INPUT8                2608
#define IDC_INFO_UDP_SENDMSG            2608
#define IDC_CHECK_INPUT9                2609
#define IDC_EDIT_UDP_CPYCODE            2609
#define IDC_CHECK_INPUT10               2610
#define IDC_EDIT_UDP_URL                2610
#define IDC_CHECK_INPUT11               2611
#define IDC_UDP_SAVEURL                 2611
#define IDC_CHECK_INPUT12               2612
#define IDC_BUTTON4                     2612
#define IDC_BTN_VALVE_HEAT              2612
#define IDC_CHECK_INPUT13               2613
#define IDC_SPIN_MARKCAM                2613
#define IDC_CHECK_INPUT14               2614
#define IDC_SPIN2                       2614
#define IDC_SPIN_NEEDLECAM              2614
#define IDC_BUTTON5                     2614
#define IDC_BTN_CTRL_SAVE_HEIGHT_DATA   2614
#define IDC_CHECK_INPUT15               2615
#define IDC_EDIT_MESMIN                 2615
#define IDC_CHECK_INPUT16               2616
#define IDC_EDIT_MESMAX                 2616
#define IDC_CHECK_INPUT17               2617
#define IDC_EDIT7                       2617
#define IDC_EDIT_MACHINEID              2617
#define IDC_CHECK_INPUT18               2618
#define IDC_CHECK_INPUT19               2619
#define IDC_CHECK_INPUT20               2620
#define IDC_CHECK_INPUT21               2621
#define IDC_CHECK_INPUT22               2622
#define IDC_CHECK_INPUT23               2623
#define IDC_CHECK_INPUT24               2624
#define IDC_CHECK_INPUT25               2625
#define IDC_CHECK_INPUT26               2626
#define IDC_CHECK_INPUT27               2627
#define IDC_CHECK_INPUT28               2628
#define IDC_CHECK_INPUT29               2629
#define IDC_CHECK_INPUT30               2630
#define IDC_CHECK_INPUT31               2631
#define IDC_CHECK_OUTPUT0               2632
#define IDC_CHECK_OUTPUT1               2633
#define IDC_CHECK_OUTPUT2               2634
#define IDC_CHECK_OUTPUT3               2635
#define IDC_CHECK_OUTPUT4               2636
#define IDC_CHECK_OUTPUT5               2637
#define IDC_CHECK_OUTPUT6               2638
#define IDC_CHECK_OUTPUT7               2639
#define IDC_CHECK_OUTPUT8               2640
#define IDC_CHECK_OUTPUT9               2641
#define IDC_CHECK_OUTPUT10              2642
#define IDC_CHECK_OUTPUT11              2643
#define IDC_CHECK_OUTPUT12              2644
#define IDC_CHECK_OUTPUT13              2645
#define IDC_CHECK_OUTPUT14              2646
#define IDC_CHECK_OUTPUT15              2647
#define IDC_CHECK_OUTPUT16              2648
#define IDC_CHECK_OUTPUT17              2649
#define IDC_CHECK_OUTPUT18              2650
#define IDC_CHECK_OUTPUT19              2651
#define IDC_CHECK_OUTPUT20              2652
#define IDC_CHECK_OUTPUT21              2653
#define IDC_CHECK_OUTPUT22              2654
#define IDC_CHECK_OUTPUT23              2655
#define IDC_CHECK_OUTPUT24              2656
#define IDC_CHECK_OUTPUT25              2657
#define IDC_CHECK_OUTPUT26              2658
#define IDC_CHECK_OUTPUT27              2659
#define IDC_CHECK_OUTPUT28              2660
#define IDC_CHECK_OUTPUT29              2661
#define IDC_CHECK_OUTPUT30              2662
#define IDC_CHECK_OUTPUT31              2663
#define IDC_USERTYPE                    2700
#define IDC_BUTTON_PWD                  2701
#define IDC_ACCESS_EDIT1                2702
#define IDC_ACCESS_EDIT2                2703
#define IDC_USER_LOGOFF                 2704
#define IDC_PAMA1                       2800
#define IDC_PAMA2                       2801
#define IDC_PAMA3                       2802
#define IDC_PAMA4                       2803
#define IDC_PAMA5                       2804
#define IDC_PAMA6                       2805
#define IDC_PAMA7                       2806
#define IDC_PAMA8                       2807
#define IDC_PAMA9                       2808
#define IDC_PAMA10                      2809
#define IDC_PAMA11                      2810
#define IDC_PAMA12                      2811
#define IDC_PAMA13                      2812
#define IDC_PAMA14                      2813
#define IDC_PAMA15                      2814
#define IDC_PAMA16                      2815
#define IDC_PAMA17                      2816
#define IDC_PAMA18                      2817
#define IDC_PAMA19                      2818
#define IDC_PAMA20                      2819
#define IDC_PAMA21                      2820
#define IDC_PAMA22                      2821
#define IDC_PAMA23                      2822
#define IDC_PAMA24                      2823
#define IDC_PAMA25                      2824
#define IDC_PAMA26                      2825
#define IDC_PAMA27                      2826
#define IDC_PAMA28                      2827
#define IDC_PAMA29                      2828
#define IDC_PAMA30                      2829
#define IDC_PAMA31                      2830
#define IDC_PAMA32                      2831
#define IDC_BTV9MA                      2832
#define IDC_BTV9MA2                     2833
#define IDC_BTV9MA3                     2834
#define IDC_BTV9MA4                     2835
#define IDC_BTV9MA5                     2836
#define IDC_BTV9MA6                     2837
#define IDC_BTV9MA7                     2838
#define IDC_BTV9MA8                     2839
#define IDC_BTV9MA9                     2840
#define IDC_BTV9MA10                    2841
#define IDC_BTV9MA11                    2842
#define IDC_BTV9MA12                    2843
#define IDC_BTV9MA13                    2844
#define IDC_BTV9MA14                    2845
#define IDC_BTV9MA15                    2846
#define IDC_BTV9MA16                    2847
#define IDC_BTV9MA17                    2848
#define IDC_BTV9MA18                    2849
#define IDC_BTV9MA19                    2850
#define IDC_BTV9MA20                    2851
#define IDC_BTV9MA21                    2852
#define IDC_BTV9MA22                    2853
#define IDC_BTV9MA23                    2854
#define IDC_BTV9MA24                    2855
#define IDC_Press1                      2856
#define IDC_Press2                      2857
#define IDC_Press3                      2858
#define IDC_RESET_ALL                   2859
#define IDC_HOME_ALL                    2860
#define IDC_DISPENSING_ALL              2861
#define IDC_CLEAR_ALL                   2862
#define IDC_UNIFORM_PARAM               2863
#define IDC_SAVE_ALL                    2864
#define IDC_EDIT_START_INDEX            2900
#define IDC_EDIT_END_INDEX              2901
#define IDC_COMBO_REPAIRE_CHANNEL       2902
#define IDC_BTN_SELECT_REGION           2903
#define IDC_BTN_SINGLE_DISP             2904
#define IDC_BTN_SELECT_DISP             2905
#define IDC_BTN_ALL_DISP                2906
#define IDC_BTN_MOVE_TO                 2907
#define IDC_EDIT_CURR_INDEX             2908
#define IDC_BTN_SAFETY_POS              2909
#define IDC_BTN_SETPOS_X_NEG            3000
#define IDC_BTN_SETPOS_X_POS            3001
#define IDC_BTN_SETPOS_Y_NEG            3002
#define IDC_BTN_SETPOS_Y_POS            3003
#define IDC_BTN_SETPOS_Z_NEG            3004
#define IDC_BTN_SETPOS_Z_POS            3005
#define IDC_SLIDER_SETPOS_SPEED         3006
#define IDC_EDIT_SETPOS_SPEED           3007
#define IDC_EDIT_SETPOS_POS_X           3008
#define IDC_EDIT_SETPOS_POS_Y           3009
#define IDC_EDIT_SETPOS_POS_Z           3010
#define IDC_EDIT_SETPOS_PROMPT          3011
#define IDC_BTN_SETPOS_NEXT             3012
#define IDC_LIST_PATH                   3100
#define IDC_BTN_CUSTOM_X_NEG            3101
#define IDC_BTN_CUSTOM_X_POS            3102
#define IDC_BTN_CUSTOM_Y_NEG            3103
#define IDC_BTN_CUSTOM_Y_POS            3104
#define IDC_BTN_CUSTOM_ZA_NEG           3105
#define IDC_BTN_CUSTOM_ZA_POS           3106
#define IDC_EDIT_CUSTOM_SPEED           3107
#define IDC_SLIDER_CUSTOM_SPEED         3108
#define IDC_EDIT_CUSTOM_CURRENT_X_POS   3109
#define IDC_EDIT_CUSTOM_CURRENT_Y_POS   3110
#define IDC_EDIT_CUSTOM_CURRENT_ZA_POS  3111
#define IDC_EDIT_CUSTOM_X_POS           3112
#define IDC_EDIT_CUSTOM_Y_POS           3113
#define IDC_EDIT_CUSTOM_ZA_POS          3114
#define IDC_BTN_CUSTOM_SAVE             3115
#define IDC_BTN_CUSTOM_AUTO_ALIGN       3116
#define IDC_BTN_CUSTOM_INSERT           3117
#define IDC_BTN_CUSTOM_MODIFY           3118
#define IDC_BTN_CUSTOM_DELET            3119
#define IDC_BTN_CUSTOM_MOVE             3120
#define IDC_EDIT_CUSTOM_LABEL_X         3121
#define IDC_EDIT_CUSTOM_LABEL_Y         3122
#define IDC_EDIT_CUSTOM_LABEL_ZA        3123
#define IDC_BTN_CUSTOM_LABEL_SAVE       3124
#define IDC_BTN_AUTO_ALIGN_X_NEG        3200
#define IDC_BTN_AUTO_ALIGN_X_POS        3201
#define IDC_BTN_AUTO_ALIGN_Y_NEG        3202
#define IDC_BTN_AUTO_ALIGN_Y_POS        3203
#define IDC_BTN_AUTO_ALIGN_ZA_NEG       3204
#define IDC_BTN_AUTO_ALIGN_ZA_POS       3205
#define IDC_SLIDER_AUTO_ALIGN_SPEED     3206
#define IDC_EDIT_AUTO_ALIGN_SPEED       3207
#define IDC_EDIT_AUTO_ALIGN_CURRENT_X   3208
#define IDC_EDIT_AUTO_ALIGN_CURRENT_Y   3209
#define IDC_EDIT_AUTO_ALIGN_CURRENT_ZA  3210
#define IDC_EDIT_AUTO_ALIGN_HEIGHT_VALUE 3211
#define IDC_EDIT_AUTO_ALIGN_PROMPT      3212
#define IDC_BTN_AUTO_ALIGN_NEXT         3213
#define IDC_STATIC_AUTO_ALIGN_PICTURE_CONTROL 3214
#define IDC_EDIT_HEIGHT_POS_CURRENT_X   3300
#define IDC_EDIT_HEIGHT_POS_CURRENT_Y   3301
#define IDC_EDIT_HEIGHT_POS_CURRENT_ZA  3302
#define IDC_BTN_HEIGHT_POS_X_NEG        3303
#define IDC_BTN_HEIGHT_POS_X_POS        3304
#define IDC_BTN_HEIGHT_POS_Y_NEG        3305
#define IDC_BTN_HEIGHT_POS_Y_POS        3306
#define IDC_BTN_HEIGHT_POS_ZA_NEG       3307
#define IDC_BTN_HEIGHT_POS_ZA_POS       3308
#define IDC_SLIDER_HEIGHT_POS_SPEED     3309
#define IDC_EDIT_HEIGHT_POS_SPEED       3310
#define IDC_EDIT_HEIGHT_POS_PROMPT      3311
#define IDC_BTN_HEIGHT_POS_NEXT         3312
#define IDC_STATIC_HEIGHT_POS_PICTURE_CONTROL 3313
#define IDC_BTN_BALANCE_RESULT_IMMEDIATE 3437
#define IDC_BTN_BALANCE_RESULT_STABLE   3438
#define IDC_EDIT_PROMPT_INFO            3500
#define IDC_SLIDER_SET_MARK_EXPOSURE_TIME 3600
#define IDC_SLIDER_SET_MARK_GAIN        3601
#define IDC_EDIT_SET_MARK_CALIBRATION_A 3602
#define IDC_EDIT_SET_MARK_CALIBRATION_B 3603
#define IDC_EDIT_SET_MARK_CALIBRATION_C 3604
#define IDC_EDIT_SET_MARK_CALIBRATION_D 3605
#define IDC_EDIT_SET_MARK_EXPOSURE_TIME 3606
#define IDC_EDIT_SET_MARK_GAIN          3607
#define IDC_COMBO_SET_MARK_SELECT       3608
#define IDC_EDIT_SET_MARK_ACCEPTANCE    3609
#define IDC_EDIT_SET_MARK_ANGLE         3610
#define IDC_EDIT_SET_MARK_CURRENT_X     3611
#define IDC_EDIT_SET_MARK_CURRENT_Y     3612
#define IDC_EDIT_SET_MARK_CURRENT_Z     3613
#define IDC_EDIT_SET_MARK_IMAGE_POS_X   3614
#define IDC_EDIT_SET_MARK_IMAGE_POS_Y   3615
#define IDC_EDIT_SET_MARK_IMAGE_POS_Z   3616
#define IDC_EDIT_SET_MARK_LEARN_WIN_LEFT 3617
#define IDC_EDIT_SET_MARK_LEARN_WIN_RIGHT 3618
#define IDC_EDIT_SET_MARK_LEARN_WIN_TOP 3619
#define IDC_EDIT_SET_MARK_LEARN_WIN_BOTTOM 3620
#define IDC_EDIT_SET_MARK_ROI_LEFT      3621
#define IDC_EDIT_SET_MARK_ROI_RIGHT     3622
#define IDC_EDIT_SET_MARK_ROI_TOP       3623
#define IDC_EDIT_SET_MARK_ROI_BOTTOM    3624
#define IDC_EDIT_SET_MARK_RESULT_SCORE  3625
#define IDC_EDIT_SET_MARK_RESULT_CENTER_X 3626
#define IDC_EDIT_SET_MARK_RESULT_CENTER_Y 3627
#define IDC_EDIT_SET_MARK_RESULT_ANGLE  3628
#define IDC_BTN_SET_MARK_SCALE          3629
#define IDC_BTN_SET_MARK_GRABPOS        3630
#define IDC_BTN_SET_MARK_NEWPIC         3631
#define IDC_BTN_SET_MARK_SAVE_LEARN_WIN 3632
#define IDC_BTN_SET_MARK_SAVE_ROI       3633
#define IDC_BTN_SET_MARK_TEST           3634
#define IDC_BTN_SET_MARK_SAVE_MODEL     3635
#define IDC_BTN_SET_MARK_SEARCH         3636
#define IDC_BTN_SET_MARK_MOVE_CENTER    3637
#define IDC_BTN_SET_MARK_SHOW_LEARN_WIN 3638
#define IDC_BTN_SET_MARK_SAVE_CENTER    3639
#define IDC_BTN_SET_MARK_CLEAR          3640
#define IDC_STATIC_SET_MARK_PIC         3641
#define IDC_COMBO_IMAGE_SELECT_INDEX    3700
#define IDC_BTN_MOVE_IMAGE_POS          3701
#define IDC_BTN_SET_IMAGE_POS           3702
#define IDC_BTN_SEARCH_IMAGE            3703
#define IDC_EDIT_IMAGE_NUM              3704
#define IDC_BTN_IMAGE_X_NEG             3705
#define IDC_BTN_IMAGE_X_POS             3706
#define IDC_BTN_IMAGE_Y_NEG             3707
#define IDC_BTN_IMAGE_Y_POS             3708
#define IDC_BTN_IMAGE_ZA_NEG            3709
#define IDC_BTN_IMAGE_ZA_POS            3710
#define IDC_SLIDER_IMAGE_SPEED          3711
#define IDC_EDIT_IMAGE_SPEED            3712
#define IDC_EDIT_IMAGE_X_POS            3713
#define IDC_EDIT_IMAGE_Y_POS            3714
#define IDC_EDIT_IMAGE_ZA_POS           3715
#define IDC_EDIT_IMAGE_PROMPT           3716
#define IDC_BTN_IMAGE_NEXT              3718
#define IDC_STATIC_IMAGE_PICTURE_CONTROL 3719
#define IDC_BTN_MANUAL_ALIGN_X_NEG      3800
#define IDC_BTN_MANUAL_ALIGN_X_POS      3801
#define IDC_BTN_MANUAL_ALIGN_Y_NEG      3802
#define IDC_BTN_MANUAL_ALIGN_Y_POS      3803
#define IDC_SLIDER_MANUAL_ALIGN_SPEED   3804
#define IDC_EDIT_MANUAL_ALIGN_SPEED     3805
#define IDC_EDIT_MANUAL_ALIGN_CURRENT_X 3806
#define IDC_EDIT_MANUAL_ALIGN_CURRENT_Y 3807
#define IDC_STATIC_MANUAL_ALIGN_PICTURE_CONTROL 3808
#define IDC_BTN_DEBUG_NEEDLE_X_NEG      3900
#define IDC_BTN_DEBUG_NEEDLE_X_POS      3901
#define IDC_BTN_DEBUG_NEEDLE_Y_NEG      3902
#define IDC_BTN_DEBUG_NEEDLE_Y_POS      3903
#define IDC_BTN_DEBUG_NEEDLE_Z_NEG      3904
#define IDC_BTN_DEBUG_NEEDLE_Z_POS      3905
#define IDC_SLIDER_DEBUG_NEEDLE_SPEED   3910
#define IDC_EDIT_DEBUG_NEEDLE_SPEED     3911
#define IDC_STATIC_DEBUG_NEEDLE_PICTURE 3920
#define IDC_BTN_DEBUG_NEXT              3923
#define IDC_COMBO_CONFIGURE_HEIGHT_SENSOR 4000
#define IDC_COMBO_CONFIGURE_VALVE_NUM   4001
#define IDC_COMBO_CONFIGURE_PLC_TYPE    4002
#define IDC_COMBO_CONFIGURE_VALVE_TYPE  4003
#define IDC_COMBO_CONFIGURE_HEIGHT_SENSOR_TYPE 4004
#define IDC_COMBO_CONFIGURE_DETECT_CAMERA_TYPE 4005
#define IDC_SLIDER_PAD_DETECT_EXPOSURE_TIME 4100
#define IDC_EDIT_PAD_DETECT_EXPOSURE_TIME 4101
#define IDC_SLIDER_PAD_DETECT_GAIN      4102
#define IDC_EDIT_PAD_DETECT_GAIN        4103
#define IDC_EDIT_PAD_DETECT_CALIBRATION_A 4104
#define IDC_EDIT_PAD_DETECT_CALIBRATION_B 4105
#define IDC_EDIT_PAD_DETECT_CALIBRATION_C 4106
#define IDC_EDIT_PAD_DETECT_CALIBRATION_D 4107
#define IDC_COMBO_PAD_DETECT_SELECT     4108
#define IDC_EDIT_PAD_DETECT_ACCEPTANCE  4109
#define IDC_EDIT_PAD_DETECT_ANGLE       4110
#define IDC_EDIT_PAD_DETECT_CURRENT_X   4111
#define IDC_EDIT_PAD_DETECT_CURRENT_Y   4112
#define IDC_EDIT_PAD_DETECT_CURRENT_Z   4113
#define IDC_EDIT_PAD_DETECT_IMAGE_POS_X 4114
#define IDC_EDIT_PAD_DETECT_IMAGE_POS_Y 4115
#define IDC_EDIT_PAD_DETECT_IMAGE_POS_Z 4116
#define IDC_EDIT_PAD_DETECT_LEARN_WIN_LEFT 4117
#define IDC_EDIT_PAD_DETECT_LEARN_WIN_RIGHT 4118
#define IDC_EDIT_PAD_DETECT_LEARN_WIN_TOP 4119
#define IDC_EDIT_PAD_DETECT_LEARN_WIN_BOTTOM 4120
#define IDC_EDIT_PAD_DETECT_ROI_LEFT    4121
#define IDC_EDIT_PAD_DETECT_ROI_RIGHT   4122
#define IDC_EDIT_PAD_DETECT_ROI_TOP     4123
#define IDC_EDIT_PAD_DETECT_ROI_BOTTOM  4124
#define IDC_EDIT_PAD_DETECT_RESULT_SCORE 4125
#define IDC_EDIT_PAD_DETECT_RESULT_ANGLE 4126
#define IDC_EDIT_PAD_DETECT_RESULT_CENTER_X 4127
#define IDC_EDIT_PAD_DETECT_RESULT_CENTER_Y 4128
#define IDC_STATIC_PAD_DETECT_PIC       4129
#define IDC_BTN_PAD_DETECT_SCALE        4130
#define IDC_BTN_PAD_DETECT_GRABPOS      4131
#define IDC_BTN_PAD_DETECT_NEWPIC       4132
#define IDC_BTN_PAD_DETECT_SAVE_LEARN_WIN 4133
#define IDC_BTN_PAD_DETECT_SHOW_LEARN_WIN 4134
#define IDC_BTN_PAD_DETECT_SAVE_ROI     4135
#define IDC_BTN_PAD_DETECT_TEST         4136
#define IDC_BTN_PAD_DETECT_SAVE_MODEL   4137
#define IDC_BTN_PAD_DETECT_SEARCH       4138
#define IDC_BTN_PAD_DETECT_MOVE_CENTER  4139
#define IDC_BTN_PAD_DETECT_SAVE_CENTER  4140
#define IDC_BTN_PAD_DETECT_CLEAR        4141
#define IDC_BTN_HEIGHT_CALIB_X_NEG      4200
#define IDC_BTN_HEIGHT_CALIB_X_POS      4201
#define IDC_BTN_HEIGHT_CALIB_Y_NEG      4202
#define IDC_BTN_HEIGHT_CALIB_Y_POS      4203
#define IDC_BTN_HEIGHT_CALIB_Z_NEG      4204
#define IDC_BTN_HEIGHT_CALIB_Z_POS      4205
#define IDC_SLIDER_HEIGHT_CALIB_SPEED   4206
#define IDC_EDIT_HEIGHT_CALIB_SPEED     4207
#define IDC_BTN_HEIGHT_CALIB_SWITCH     4208
#define IDC_EDIT_HEIGHT_CALIB_STANDARD_VALUE 4209
#define IDC_EDIT_HEIGHT_CALIB_CURRENT_VALUE 4210
#define IDC_EDIT_HEIGHT_CALIB_HIGHT_STANDARD_VALUE 4211
#define IDC_EDIT_HEIGHT_CALIB_HIGHT_CURRENT_VALUE 4212
#define IDC_EDIT_HEIGHT_CALIB_PROMPT    4213
#define IDC_BTN_HEIGHT_CALIB_NEXT       4214
#define IDC_EDIT_DETECT_CALIB_PROMPT    4300
#define IDC_BTN_DETECT_CALIB_NEXT       4301
#define IDC_STATIC_DETECT_CALIB_PICTURE 4302
#define IDC_BTN_FIRST_IN_POS            4400
#define IDC_BTN_MANUAL_UNLOAD           4401
#define IDC_BTN_FIRST_OUT_POS           4402
#define IDC_BTN_LABEL_X_NEG             4500
#define IDC_BTN_LABEL_X_POS             4501
#define IDC_BTN_LABEL_Y_NEG             4502
#define IDC_BTN_LABEL_Y_POS             4503
#define IDC_BTN_LABEL_ZA_NEG            4504
#define IDC_BTN_LABEL_ZA_POS            4505
#define IDC_BTN_LABEL_ZB_NEG            4506
#define IDC_BTN_LABEL_ZB_POS            4507
#define IDC_BTN_LABEL_ZC_NEG            4508
#define IDC_BTN_LABEL_ZC_POS            4509
#define IDC_SLIDER_LABEL_SPEED          4510
#define IDC_EDIT_LABEL_SPEED            4511
#define IDC_EDIT_LABEL_CURR_POS_X       4512
#define IDC_EDIT_LABEL_CURR_POS_Y       4513
#define IDC_EDIT_LABEL_CURR_POS_ZA      4514
#define IDC_EDIT_LABEL_CURR_POS_ZB      4515
#define IDC_EDIT_LABEL_CURR_POS_ZC      4516
#define IDC_EDIT_LABEL_CURR_POS_A       4517
#define IDC_EDIT_LABEL_CURR_POS_B       4518
#define IDC_EDIT_LABEL_CURR_POS_C       4519
#define IDC_EDIT_LABEL_CURR_POS_D       4520
#define IDC_EDIT_LABEL_PROMPT           4521
#define IDC_BTN_LABEL_NEXT              4522
#define IDC_STATIC_LABEL_PICTURE        4523
#define IDC_EDIT_LABEL_HEIGHT_STANDARD_VALUE 4524
#define IDC_EDIT_LABEL_HEIGHT_CURR_VALUE 4525
#define IDC_BTN_AUTO_NEEDLE_X_NEG       4600
#define IDC_BTN_AUTO_NEEDLE_X_POS       4601
#define IDC_BTN_AUTO_NEEDLE_Y_NEG       4602
#define IDC_BTN_AUTO_NEEDLE_Y_POS       4603
#define IDC_BTN_AUTO_NEEDLE_ZA_NEG      4604
#define IDC_BTN_AUTO_NEEDLE_ZA_POS      4605
#define IDC_BTN_AUTO_NEEDLE_ZB_NEG      4606
#define IDC_BTN_AUTO_NEEDLE_ZB_POS      4607
#define IDC_BTN_AUTO_NEEDLE_ZC_NEG      4608
#define IDC_BTN_AUTO_NEEDLE_ZC_POS      4609
#define IDC_SLIDER_AUTO_NEEDLE_SPEED    4610
#define IDC_EDIT_AUTO_NEEDLE_SPEED      4611
#define IDC_EDIT_AUTO_NEEDLE_CURR_POS_X 4612
#define IDC_EDIT_AUTO_NEEDLE_CURR_POS_Y 4613
#define IDC_EDIT_AUTO_NEEDLE_CURR_POS_ZA 4614
#define IDC_EDIT_AUTO_NEEDLE_CURR_POS_ZB 4615
#define IDC_EDIT_AUTO_NEEDLE_CURR_POS_ZC 4616
#define IDC_EDIT_AUTO_NEEDLE_CURR_POS_A 4617
#define IDC_EDIT_AUTO_NEEDLE_CURR_POS_B 4618
#define IDC_EDIT_AUTO_NEEDLE_CURR_POS_C 4619
#define IDC_EDIT_AUTO_NEEDLE_CURR_POS_D 4620
#define IDC_EDIT_AUTO_NEEDLE_ENC_POS_X  4621
#define IDC_EDIT_AUTO_NEEDLE_ENC_POS_Y  4622
#define IDC_EDIT_AUTO_NEEDLE_ENC_POS_ZA 4623
#define IDC_EDIT_AUTO_NEEDLE_ENC_POS_ZB 4624
#define IDC_EDIT_AUTO_NEEDLE_ENC_POS_ZC 4625
#define IDC_EDIT_AUTO_NEEDLE_ENC_POS_A  4626
#define IDC_EDIT_AUTO_NEEDLE_ENC_POS_B  4627
#define IDC_EDIT_AUTO_NEEDLE_ENC_POS_C  4628
#define IDC_EDIT_AUTO_NEEDLE_ENC_POS_D  4629
#define IDC_EDIT_AUTO_NEEDLE_VEL        4630
#define IDC_EDIT_AUTO_NEEDLE_ACC        4631
#define IDC_EDIT_AUTO_NEEDLE_PITCH      4632
#define IDC_EDIT_AUTO_NEEDLE_GLUE       4633
#define IDC_EDIT_AUTO_NEEDLE_ACCEPTANCE 4634
#define IDC_EDIT_AUTO_NEEDLE_ANGLE      4635
#define IDC_EDIT_AUTO_NEEDLE_ERROR_X    4636
#define IDC_EDIT_AUTO_NEEDLE_ERROR_Y    4637
#define IDC_EDIT_AUTO_NEEDLE_ADJUST_COUNT 4638
#define IDC_EDIT_AUTO_NEEDLE_STEP_X_COUNT 4639
#define IDC_EDIT_AUTO_NEEDLE_STEP_X_PITCH 4640
#define IDC_EDIT_AUTO_NEEDLE_STEP_Y_COUNT 4641
#define IDC_EDIT_AUTO_NEEDLE_STEP_Y_PITCH 4642
#define IDC_EDIT_AUTO_NEEDLE_CALIB_A    4643
#define IDC_EDIT_AUTO_NEEDLE_CALIB_B    4644
#define IDC_EDIT_AUTO_NEEDLE_CALIB_C    4645
#define IDC_EDIT_AUTO_NEEDLE_CALIB_D    4646
#define IDC_EDIT_AUTO_NEEDLE_RESULT_SCORE 4647
#define IDC_EDIT_AUTO_NEEDLE_RESULT_ANGLE 4648
#define IDC_EDIT_AUTO_NEEDLE_RESULT_CENTERX 4649
#define IDC_EDIT_AUTO_NEEDLE_RESULT_CENTERY 4650
#define IDC_EDIT_AUTO_NEEDLE_THRESHOLD  4651
#define IDC_EDIT_AUTO_NEEDLE_AREA_MAX   4652
#define IDC_EDIT_AUTO_NEEDLE_AREA_MIN   4653
#define IDC_EDIT_AUTO_NEEDLE_LENGTH_MAX 4654
#define IDC_EDIT_AUTO_NEEDLE_LENGTH_MIN 4655
#define IDC_EDIT_AUTO_NEEDLE_HEIGHT_MAX 4656
#define IDC_EDIT_AUTO_NEEDLE_HEIGHT_MIN 4657
#define IDC_EDIT_AUTO_NEEDLE_START_POS_X 4658
#define IDC_EDIT_AUTO_NEEDLE_START_POS_Y 4659
#define IDC_EDIT_AUTO_NEEDLE_START_POS_ZA 4660
#define IDC_EDIT_AUTO_NEEDLE_START_POS_ZB 4661
#define IDC_EDIT_AUTO_NEEDLE_START_POS_ZC 4662
#define IDC_STATIC_AUTO_NEEDLE_PICTURE  4663
#define IDC_RADIO_AUTO_NEEDLE_GRAY      4664
#define IDC_RADIO_AUTO_NEEDLE_BLOB      4665
#define IDC_BTN_AUTO_NEEDLE_SAVE_POS    4666
#define IDC_BTN_AUTO_NEEDLE_MOVE_POS    4667
#define IDC_BTN_AUTO_NEEDLE_RESET       4668
#define IDC_BTN_AUTO_NEEDLE_SAVE_PARAME 4669
#define IDC_BTN_AUTO_NEEDLE_ADJUST_NEEDLE_ONE 4670
#define IDC_BTN_AUTO_NEEDLE_ADJUST_NEEDLE_TWO 4671
#define IDC_BTN_AUTO_NEEDLE_ADJUST_NEEDLE_THREE 4672
#define IDC_BTN_AUTO_NEEDLE_ADJUST_NEEDLE 4673
#define IDC_BTN_AUTO_NEEDLE_SAVE_ROI    4674
#define IDC_BTN_AUTO_NEEDLE_SAVE_MODEL  4675
#define IDC_BTN_AUTO_NEEDLE_SAVE_MODEL_WIN 4676
#define IDC_BTN_AUTO_NEEDLE_NEEDLE_ONE  4677
#define IDC_BTN_AUTO_NEEDLE_NEEDLE_TWO  4678
#define IDC_BTN_AUTO_NEEDLE_NEEDLE_THREE 4679
#define IDC_BTN_AUTO_NEEDLE_CALIB       4680
#define IDC_EDIT_PROMPT                 5000
#define IDC_PIC_NEEDLEONE               5001
#define IDC_BTN_NEEDLEONE_X_NEG_NDLEONE 5002
#define IDC_BTN_NEEDLEONE_X_POS_NDLEONE 5003
#define IDC_BTN_NEEDLEONE_Y_NEG_NDLEONE 5004
#define IDC_BTN_NEEDLEONE_Y_POS_NDLEONE 5005
#define IDC_BTN_NEEDLEONE_Z_NEG_NDLEONE 5006
#define IDC_BTN_NEEDLEONE_Z_POS_NDLEONE 5007
#define IDC_BTN_LT_NDLEONE              5008
#define IDC_BTN_RT_NDLEONE              5009
#define IDC_BTN_LB_NDLEONE              5010
#define IDC_BTN_RB_NDLEONE              5011
#define IDC_BTN_NDLEONE                 5012
#define IDC_BTN_ZLOCK_NDLEONE           5013
#define IDC_BTN_LEARNMODEL_NDLEONE      5014
#define IDC_BTN_COMPUTESCALE_NDLEONE    5015
#define IDC_BTN_SEARCHMODEL_NDLEONE     5016
#define IDC_BTN_MOVETOCENTER_NDLEONE    5017
#define IDC_PIC_NEEDLETWO               5101
#define IDC_BTN_NEEDLETWO_A_NEG_NDLTWO  5102
#define IDC_BTN_NEEDLETWO_A_POS_NDLTWO  5103
#define IDC_BTN_NEEDLETWO_B_NEG_NDLTWO  5104
#define IDC_BTN_NEEDLETWO_B_POS_NDLTWO  5105
#define IDC_BTN_NEEDLETWO_Z_NEG_NDLTWO  5106
#define IDC_BTN_NEEDLETWO_Z_POS_NDLTWO  5107
#define IDC_BTN_LT_NDLTWO               5108
#define IDC_BTN_RT_NDLTWO               5109
#define IDC_BTN_LB_NDLTWO               5110
#define IDC_BTN_RB_NDLTWO               5111
#define IDC_BTN_NDLTWO                  5112
#define IDC_BTN_ZLOCK_NDLTWO            5113
#define IDC_BTN_LEARNMODEL_NDLTWO       5114
#define IDC_BTN_COMPUTESCALE_NDLTWO     5115
#define IDC_BTN_SEARCHMODEL_NDLTWO      5116
#define IDC_BTN_MOVETOCENTER_NDLTWO     5117
#define IDC_PIC_NEEDLETHREE             5201
#define IDC_BTN_NEEDLETHREE_C_NEG_NDLTHREE 5202
#define IDC_BTN_NEEDLETHREE_C_POS_NDLTHREE 5203
#define IDC_BTN_NEEDLETHREE_D_NEG_NDLTHREE 5204
#define IDC_BTN_NEEDLETHREE_D_POS_NDLTHREE 5205
#define IDC_BTN_NEEDLETHREE_Z_NEG_NDLTHREE 5206
#define IDC_BTN_NEEDLETHREE_Z_POS_NDLTHREE 5207
#define IDC_BTN_LT_NDLTHREE             5208
#define IDC_BTN_LB_NDLTHREE             5209
#define IDC_BTN_RT_NDLTHREE             5210
#define IDC_BTN_RB_NDLTHREE             5211
#define IDC_BTN__NDLTHREE               5212
#define IDC_BTN_ZLOCK_NDLTHREE          5213
#define IDC_BTN_LEARNMODEL_NDLTHREE     5214
#define IDC_BTN_COMPUTESCALE_NDLTHREE   5215
#define IDC_BTN_SEARCHMODEL_NDLTHREE    5216
#define IDC_BTN_MOVETOCENTER_NDLTHREE   5217
#define IDC_STATIC_NEEDLECAMERA         5301
#define IDC_BTN_NEEDLE_X_NEG_INCAM      5302
#define IDC_BTN_NEEDLE_X_POS_INCAM      5303
#define IDC_BTN_NEEDLE_Y_NEG_INCAM      5304
#define IDC_BTN_NEEDLE_Y_POS_INCAM      5305
#define IDC_BTN_NEEDLE_Z_NEG_INCAM      5306
#define IDC_BTN_NEEDLE_Z_POS_INCAM      5307
#define IDC_BTN_LP_INCAM                5308
#define IDC_BTN_LB_INCAM                5309
#define IDC_BTN_RT_INCAM                5310
#define IDC_BTN_RB_INCAM                5311
#define IDC_BTN_MID_INCAM               5312
#define IDC_BTN_ZLOCK_INCAM             5313
#define IDC_BTN_LEARNMODEL_INCAM        5314
#define IDC_BTN_COMPUTESCALE_INCAM      5315
#define IDC_BTN_SEARCHMODEL_INCAM       5316
#define IDC_BTN_MOVETOCENTER_INCAM      5317
#define IDOVER                          5400
#define IDC_BTN_NEEDLETHREE             5402
#define IDC_BTN_NEEDLETWO               5403
#define IDC_BTN_START                   5404
#define IDC_BTN_NEEDLEONE               5405
#define IDC_PIC                         5406
#define IDC_BTNAGAIN                    5409
#define IDC_PIC_CAMERA_ADJUST           5500
#define IDC_BTN_X_NEG_INCAMADJUST       5501
#define IDC_BTN_X_POS_INCAMADJUST       5502
#define IDC_BTN_Y_NEG_INCAMADJUST       5503
#define IDC_BTN_Y_POS_INCAMADJUST       5504
#define IDC_BTN_Z_NEG_INCAMADJUST       5505
#define IDC_BTN_Z_POS_INCAMADJUST       5506
#define IDC_BTN_LP_INCAMADJUST          5507
#define IDC_BTN_LB_INCAMADJUST          5508
#define IDC_BTN_RT_INCAMADJUST          5509
#define IDC_BTN_RB_INCAMADJUST          5510
#define IDC_BTN_MID_INCAMADJUST         5511
#define IDC_BTN_ZLOCK_INCAMADJUST       5512
#define IDC_BTNCAMADJ                   5513
#define IDC_PIC_NDLONEADJ               5600
#define IDC_BTN_X_NEG_NDLONEADJUST      5601
#define IDC_BTN_X_POS_NDLONEADJUST      5602
#define IDC_BTN_Y_NEG_NDLONEADJUST      5603
#define IDC_BTN_Y_POS_NDLONEADJUST      5604
#define IDC_BTN_Z_NEG_NDLONEADJUST      5605
#define IDC_BTN_Z_POS_NDLONEADJUST      5606
#define IDC_BTN_LP_NDLONEADJUST         5607
#define IDC_BTN_LB_NDLONEADJUST         5608
#define IDC_BTN_RT_NDLONEADJUST         5609
#define IDC_BTN_RB_NDLONEADJUST         5610
#define IDC_BTN_MID_NDLONEADJUST        5611
#define IDC_BTN_ZLOCK_NDLONEADJUST      5612
#define IDC_BTNONEADJ                   5613
#define IDC_PIC_NDLTWOADJ               5700
#define IDC_BTN_A_NEG_NDLTWOADJUST      5701
#define IDC_BTN_A_POS_NDLTWOADJUST      5702
#define IDC_BTN_B_NEG_NDLTWOADJUST      5703
#define IDC_BTN_B_POS_NDLTWOADJUST      5704
#define IDC_BTN_Z_NEG_NDLTWOADJUST      5705
#define IDC_BTN_Z_POS_NDLTWOADJUST      5706
#define IDC_BTN_LP_NDLTWOADJUST         5707
#define IDC_BTN_LB_NDLTWOADJUST         5708
#define IDC_BTN_RT_NDLTWOADJUST         5709
#define IDC_BTN_RB_NDLTWOADJUST         5710
#define IDC_BTN_MID_NDLTWOADJUST        5711
#define IDC_BTN_ZLOCK_NDLTWOADJUST      5712
#define IDC_BTNTWOADJ                   5713
#define IDC_PIC_NDLTHREEADJ             5800
#define IDC_BTN_C_NEG1_NDLTHREEADJUST   5801
#define IDC_BTN_C_NEG_NDLTHREEADJUST    5801
#define IDC_BTN_C_POS1_NDLTHREEADJUST   5802
#define IDC_BTN_C_POS_NDLTHREEADJUST    5802
#define IDC_BTN_D_NEG_NDLTHREEADJUST    5803
#define IDC_BTN_D_POS_NDLTHREEADJUST    5804
#define IDC_BTN_Z_NEG_NDLTHREEADJUST    5805
#define IDC_BTN_Z_POS_NDLTHREEADJUST    5806
#define IDC_BTN_LP_NDLTHREEADJUST       5807
#define IDC_BTN_LB_NDLTHREEADJUST       5808
#define IDC_BTN_RT_NDLTHREEADJUST       5809
#define IDC_BTN_RB_NDLTHREEADJUST       5810
#define IDC_BTN_MID_NDLTHREEADJUST      5811
#define IDC_BTN_ZLOCK_NDLTHREEADJUST    5812
#define IDC_BTNTHREEADJ                 5813
#define IDC_BTN_X_NEG                   5900
#define IDC_BTN_X_POS                   5901
#define IDC_BTN_Y_NEG                   5902
#define IDC_BTN_Y_POS                   5903
#define IDC_BTN_ZA_NEG                  5904
#define IDC_BTN_ZA_POS                  5905
#define IDC_EDIT_INFO                   5906
#define IDC_RADIO_DOT                   6000
#define IDC_RADIO_LINE_VERTICAL         6001
#define IDC_RADIO_LINE_HORIZONTAL       6002
#define IDC_RADIO_RECTANGLE             6003
#define IDC_RADIO_HELIX                 6004
#define IDC_RADIO_CUSTOM                6005
#define IDC_RADIO_CIRCLE                6006
#define IDC_RADIO_MULTI                 6007
#define IDC_RADIO_COMPLEX               6008
#define IDC_PAMA36                      6100
#define IDC_PAMA37                      6101
#define IDC_PAMA38                      6102

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        436
#define _APS_NEXT_COMMAND_VALUE         32871
#define _APS_NEXT_CONTROL_VALUE         2618
#define _APS_NEXT_SYMED_VALUE           367
#endif
#endif
